language: android
sudo: true
git:
  depth: 3
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28
install:
  # - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "platforms;android-28"

before_script:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew
script:
  - ./gradlew assembleDebug
  - ./gradlew test --info