language: android
env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
  global:   #Optional 
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins
sudo: true
git:
  depth: 3
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
      - sys-img-armeabi-v7a-android-19
      - sys-img-armeabi-v7a-android-21
install:
  # - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "platforms;android-28"

before_script:
  - chmod +x gradlew
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator
  - android-wait-for-emulator             #Run wait for the emulator script.
  - adb devices                           #Display list of devices
  - adb shell input keyevent 82 &

script:
  - ./gradlew assembleDebug
  - ./gradlew test --info
  - ./gradlew connectedAndroidTest