language: android
sudo: true
git:
  depth: 3
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28
install:
  # - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "platforms;android-28"

before_script:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
  - ./gradlew assembleDebug
  - ./gradlew test --info
  - android-wait-for-emulator
  - adb devices   #Display list of devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace   