name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.10
          distribution: 'adopt'
          cache: gradle

      - name: Write to local.properties
        run: |
          echo BACKTRACE_SUBMISSION_URL=\"https://submit.backtrace.io/yolo/2dd86e8e779d1fc7e22e7b19a9489abeedec3b1426abe7e2209888e92362fba4/json\" > ./local.properties
          echo BACKTRACE_CORONER_URL=\"https://yolo.sp.backtrace.io/api/query?project=android-library\" >> ./local.properties
          echo BACKTRACE_CORONER_TOKEN=\"4d1c52a829fa4b53c3c421d163f327e6bfaa5304e756a71249174ab2e1603f8a\" >> ./local.properties

      - name: Build and check
        run: ./gradlew assembleDebug assembleDebugAndroidTest check

      - name: Upload example-app APK
        uses: actions/upload-artifact@v3
        with:
          name: example-app-debug.apk
          path: example-app/build/outputs/apk/debug/example-app-debug.apk

      - name: Upload example-app Test APK
        uses: actions/upload-artifact@v3
        with:
          name: example-app-debug-androidTest.apk
          path: example-app/build/outputs/apk/androidTest/debug/example-app-debug-androidTest.apk

      - name: Upload backtrace-library AAR
        uses: actions/upload-artifact@v3
        with:
          name: backtrace-library-debug.aar
          path: backtrace-library/build/outputs/aar/backtrace-library-debug.aar

      - name: Upload backtrace-library Test APK
        uses: actions/upload-artifact@v3
        with:
          name: backtrace-library-debug-androidTest.apk
          path: backtrace-library/build/outputs/apk/androidTest/debug/backtrace-library-debug-androidTest.apk

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      fail-fast: false
      matrix:
        test-apk: [example-app-debug-androidTest.apk, backtrace-library-debug-androidTest.apk]

    steps:
      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: example-app-debug.apk

      - name: Download Test APK
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.test-apk }}

      - name: Get Saucectl
        run: curl -L https://saucelabs.github.io/saucectl/install | bash

      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true

      - name: Run Saucectl
        run: |
          saucectl configure --username ${{ secrets.SAUCE_USERNAME }} --accessKey ${{ secrets.SAUCE_ACCESS_KEY }}
          # newest Android version
          saucectl run espresso -c "" --name "From Github Actions" --app example-app-debug.apk --testApp ${{ matrix.test-apk }}  --emulator name="Android GoogleApi Emulator,platformVersion=12.0"
          # oldest Android version
          saucectl run espresso -c "" --name "From Github Actions" --app example-app-debug.apk --testApp ${{ matrix.test-apk }}  --emulator name="Android GoogleApi Emulator,platformVersion=5.1"
          # real device
          saucectl run espresso -c "" --name "From Github Actions" --app example-app-debug.apk --testApp ${{ matrix.test-apk }}  --device name="Samsung_Galaxy_S20_FE_5G_backtrace_us"
          # --device name=".*,platformVersion=6.0.1"
          # --device name="Samsung_Galaxy_S20_FE_5G_backtrace_us"
          # --device name="Samsung_Galaxy_S22_Ultra_5G_backtrace_us"
